### ISSUE TITLE
Code Does not compile

### ISSUE THREAD

**Issue by bphun** [ChewyChiyu/Doodle-Jump#1]
I can't compile your code. When I compile the launcher, this is returned: 

`DoodleJumpLauncher.java:3: error: package sprites does not exist
import sprites.Texture;
              ^
DoodleJumpLauncher.java:10: error: cannot find symbol
		new Texture();
		    ^
  symbol:   class Texture
  location: class DoodleJumpLauncher
DoodleJumpLauncher.java:11: error: cannot find symbol
		new Screen();
		    ^
  symbol:   class Screen
  location: class DoodleJumpLauncher
3 errors`

**Comment by ChewyChiyu** [comment]
well others can compile it :(
